### ISSUE TITLE
local variable 'predict_result' referenced before assignment

### ISSUE THREAD

**Issue by BlueSeven277** [DataXujing/vehicle-license-plate-recognition#1]
Hi, I tried to test. When I try to recognise your test data everything is fine. But I got an error of "local variable 'predict_result' referenced before assignment" when I try with my own .jpg images.
Thanks

**Comment by BlueSeven277** [comment]
I find this line in your code: "cv2.imwrite(os.path.join("./result",pic_file),roi)"
It seems that you saved the result of test images to "./result" folder in advance... Seems that the program cannot deal with any new image?

**Comment by DataXujing** [comment]
It can test any image what you want,you can put your new image in `test_img` folder!

**Comment by DataXujing** [comment]
Check the `card_seg.py` line 135, 159 and 166, we define the list `predict_result`,you can put your own image in test_img and debug your test code。 thank you !

**Comment by BlueSeven277** [comment]
![image](https://user-images.githubusercontent.com/15715350/69073429-6db15180-09fb-11ea-9043-0f6bdde0ac7b.png)
Hi, Thanks for replying. This images shows the error that I got when I tried to open my own car image and I already put it in "test_img" folder.

**Comment by DataXujing** [comment]
OK, please,you can find the py file `my_main_ui.py`, and comment out the`try ... exception...` structure (line 60, and line 106-107), and  also note the indentation of other codes. Find the **Wrong Location**. In my submission，this exception is at position `card_seg.py`, please check it!
