### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by DWendou94** [DataXujing/vehicle-license-plate-recognition#2]
按照你的要求安装了所有库，运行my_main_ui.py，出现AttributeError: 'MainWindow' object has no attribute 'setWindowFlag'，根据错误提示Ui_my_main_ui.py中的MainWindow.setWindowFlag有问题，但不知道怎么解决

**Comment by DataXujing** [comment]
这可能是PyQt5版本问题导致的，你可以将代码

`MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)`

修改为：

`self.setWindowFlag(QtCore.Qt.FramelessWindowHint)`

**Comment by DWendou94** [comment]
是的，我尝试成功了。非常感谢。
对了，你是用什么打包的？我对你的项目做了一些界面设计上的修改。然后用Pyinstaller打包的时候，生成的.exe文件打不开。我尝试了百度上的很多修改，都失败了。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"徐静"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 上午8:56
收件人:&nbsp;"DataXujing/vehicle-license-plate-recognition"<vehicle-license-plate-recognition@noreply.github.com&gt;;
抄送:&nbsp;"麦都叔叔"<919331129@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DataXujing/vehicle-license-plate-recognition] AttributeError (#2)




这可能是PyQt5版本问题导致的，你可以将代码
 
MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
 
修改为：
 
self.setWindowFlag(QtCore.Qt.FramelessWindowHint)

**Comment by DataXujing** [comment]
pyinstaller打包的，注意修改`.spec`文件，开始最好先把命令行开启，这样运行过程中直到出现了什么问题，最后发布时记得把命令行关掉！

**Comment by DWendou94** [comment]
非常感谢。学到了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"徐静"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 晚上11:07
收件人:&nbsp;"DataXujing/vehicle-license-plate-recognition"<vehicle-license-plate-recognition@noreply.github.com&gt;;
抄送:&nbsp;"麦都叔叔"<919331129@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DataXujing/vehicle-license-plate-recognition] AttributeError (#2)




pyinstaller打包的，注意修改.spec文件，开始最好先把命令行开启，这样运行过程中直到出现了什么问题，最后发布时记得把命令行关掉！
